name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 2.0.0+22
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_datepicker: ^29.1.41
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.0
  flutter_animarker: ^3.2.0
  file_picker: ^10.1.5
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.16.0
  flutter_rating_bar: ^4.0.1
  vibration: ^3.1.3
  shimmer: ^3.0.0
  expandable: ^5.0.1
  appinio_swiper: ^2.1.1
  pin_code_fields: ^8.0.1
  fl_chart: ^0.71.0
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.1.0
  path: ^1.9.0
  flutter_spinkit: ^5.2.1
  location: ^8.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_typeahead: ^5.2.0
  permission_handler: ^12.0.0+1
  flutter_inappwebview: ^6.0.0
  fluttertoast: ^8.2.6
  flutter_slidable: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  screenshot: ^3.0.0
  flutter_animated_button: ^2.0.3
  audioplayers: ^6.0.0
  card_swiper: ^3.0.1
  dropdown_button2: ^2.3.9
  lottie: ^3.1.2
  app_settings: ^6.1.1
  showcaseview: ^4.0.1
  dart_pusher_channels: ^1.2.2+1
  just_the_tooltip: ^0.0.12
  firebase_crashlytics: ^4.0.3
  share_plus: ^11.0.0
  flutter_keyboard_visibility: ^6.0.0
  video_thumbnail: ^0.5.6
  video_player: ^2.9.2
  chewie: ^1.8.5
  firebase_auth: ^5.3.1
  phone_numbers_parser: ^9.0.1
  flutter_inappwebview_ios: ^1.1.2
  flutter_downloader: ^1.11.8
  just_audio: ^0.10.2
  record: ^6.0.0
  ffmpeg_kit_flutter_new: ^1.2.0
  

dependency_overrides:
  sky_engine:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/
    - assets/
    - assets/icon/
    - shorebird.yaml

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
