// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuUMLHF9ztJkQnrFVZtwELKLG7J2vVbA',
    appId: '1:810616739165:web:ac70ff0c9d8fa74cdc84b4',
    messagingSenderId: '810616739165',
    projectId: 'tawselty-49dfb',
    authDomain: 'tawselty-49dfb.firebaseapp.com',
    storageBucket: 'tawselty-49dfb.firebasestorage.app',
    measurementId: 'G-W5T9DN746S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAbAIa89Fye8pNiVNBUQ7YkvbiFodFT0',
    appId: '1:810616739165:android:916480bdc73dfe6cdc84b4',
    messagingSenderId: '810616739165',
    projectId: 'tawselty-49dfb',
    storageBucket: 'tawselty-49dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLj7p2VU-RIJCSsplS3ySBz20gG98iOJo',
    appId: '1:810616739165:ios:d41f077f9958d7d8dc84b4',
    messagingSenderId: '810616739165',
    projectId: 'tawselty-49dfb',
    storageBucket: 'tawselty-49dfb.firebasestorage.app',
    iosBundleId: 'com.devu.hwiloDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLj7p2VU-RIJCSsplS3ySBz20gG98iOJo',
    appId: '1:810616739165:ios:ba60a71598b5f28edc84b4',
    messagingSenderId: '810616739165',
    projectId: 'tawselty-49dfb',
    storageBucket: 'tawselty-49dfb.firebasestorage.app',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuUMLHF9ztJkQnrFVZtwELKLG7J2vVbA',
    appId: '1:810616739165:web:f65cf33b49c7e9aadc84b4',
    messagingSenderId: '810616739165',
    projectId: 'tawselty-49dfb',
    authDomain: 'tawselty-49dfb.firebaseapp.com',
    storageBucket: 'tawselty-49dfb.firebasestorage.app',
    measurementId: 'G-SWRTMW5X5J',
  );

}